export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const LIST_USER_REQUEST = 'LIST_USER_REQUEST';
export const LIST_USER_SUCCESS = 'LIST_USER_SUCCESS';
export const LIST_USER_FAIL = 'LIST_USER_FAIL';

export const USER_ACTIVATE_REQUEST = 'USER_ACTIVATE_REQUEST';
export const USER_ACTIVATE_SUCCESS = 'USER_ACTIVATE_SUCCESS';
export const USER_ACTIVATE_FAIL = 'USER_ACTIVATE_FAIL';

export const USER_FORGOT_REQUEST = 'USER_FORGOT_REQUEST';
export const USER_FORGOT_SUCCESS = 'USER_FORGOT_SUCCESS';
export const USER_FORGOT_FAIL = 'USER_FORGOT_FAIL';

export const USER_RESET_REQUEST = 'USER_RESET_REQUEST';
export const USER_RESET_SUCCESS = 'USER_RESET_SUCCESS';
export const USER_RESET_FAIL = 'USER_RESET_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';